#!/usr/bin/env python3
import os
import gi

gi.require_version('Gtk', '3.0')

from gi.repository import Gtk, Gio
import sys

down = Gtk.PositionType.BOTTOM
up = Gtk.PositionType.TOP
left = Gtk.PositionType.LEFT
right = Gtk.PositionType.RIGHT

CURRPATH = os.path.dirname(os.path.realpath(__file__))
read_more_link = os.popen('printf "$(./curl.sh)"').read()
body_text = os.popen('curl https://www.bing.com 2>&1 | grep -oP \'id="iotd_desc".{0,715}\' | cut -d \'>\' -f2 | cut -d "<" -f1').read()
title_text = os.popen('printf "$(curl https://www.bing.com 2>&1 | grep -oP \'og:title\" content=\".{0,80}\' | cut -d \'\"\' -f3)..."').read()

class Window(Gtk.Window):
	def __init__(self):
		Gtk.Window.__init__(self, title=title_text)
		Gtk.Window.set_default_icon_from_file("icon.ico")
		
		self.set_size_request(600, 250)
		grid = Gtk.Grid()
		self.add(grid)
		
		btngrid = Gtk.Grid(expand=True)
		
		hb = Gtk.HeaderBar()
		hb.set_show_close_button(True)
		hb.props.title = title_text
		self.set_titlebar(hb)
		
		label = Gtk.Label(label=body_text)
		label.set_line_wrap(True)
		label.set_justify(Gtk.Justification.FILL)
		label.set_max_width_chars(74)
		label.set_margin_start(6)
		label.set_margin_end(6)
		
		close = Gtk.Button.new_with_mnemonic("_Close")
		close.connect("clicked", Gtk.main_quit)
		
		readmore = Gtk.Button.new_with_mnemonic("_Read _More")
		readmore.connect("clicked", self.read_more)
		
		open_pic = Gtk.Button.new_with_mnemonic("_Open _Image in _New _Tab")
		open_pic.connect("clicked", self.openpic)
		
		open_pin_in_app = Gtk.Button.new_with_mnemonic("_Open _Image in " + os.popen('printf "$(xdg-mime query default image/jpeg | tr . \" \" | awk \'{print $3}\')"').read())
		open_pin_in_app.connect("clicked", self.openpic_app)
		
		grid.attach(label, 0, 0, 1, 1)
		grid.attach_next_to(btngrid, label, down, 1, 1) 
		btngrid.attach(close, 0, 1, 1, 1)
		btngrid.attach_next_to(readmore, close, right, 1, 1)
		btngrid.attach_next_to(open_pic, readmore, right, 1, 1)
		btngrid.attach_next_to(open_pin_in_app, open_pic, right, 1, 1)
		
	def read_more(self, button):
		read_xdg = 'xdg-open "https://www.bing.com$(curl https://www.bing.com 2>&1 | grep -oPi ".{0,200}Learn more</a>" | grep -oP \'href=.{0,150}\' | cut -d \'"\' -f2)"'
		os.system(read_xdg)
		Gtk.main_quit()
		
	def openpic(self, button):
		open_xdg = 'xdg-open "$(./curl.sh)"'
		os.system(open_xdg) 
		Gtk.main_quit()
			
			
	def openpic_app(self, button):
		os.system('mkdir -p $HOME/Pictures/bpotd')
		curl_xdg = "xdg-open $HOME/Pictures/bpotd/$(date +%F).jpg"
		os.system("curl $(./curl.sh) -o $HOME/Pictures/bpotd/$(date +%F).jpg; "+curl_xdg)
	
window = Window()
window.connect("destroy", Gtk.main_quit)
window.show_all()
Gtk.main()
