#!/usr/bin/env python3

import os
from gi.repository import Gtk as gtk, AppIndicator3 as appindicator

CURRPATH = os.path.dirname(os.path.realpath(__file__))

def main():
  indicator = appindicator.Indicator.new("customtray", CURRPATH+"/icon.ico", appindicator.IndicatorCategory.APPLICATION_STATUS)
  indicator.set_status(appindicator.IndicatorStatus.ACTIVE)
  indicator.set_menu(menu())
  gtk.main()

def menu():
  menu = gtk.Menu()
  
  exitimg = gtk.Image()
  exitimg.set_from_icon_name("gtk-close", 24)
  exittray = gtk.ImageMenuItem('Quit')
  exittray.set_image(exitimg)
  exittray.set_always_show_image(True)
  exittray.connect('activate', quit)
  
  hr = gtk.SeparatorMenuItem()

  aboutimg = gtk.Image()
  aboutimg.set_from_file("icon.ico")
  aboutbpotd = gtk.ImageMenuItem('About bpotd')
  aboutbpotd.set_image(aboutimg)
  aboutbpotd.set_always_show_image(True)
  aboutbpotd.connect('activate', bpotdabout)
  
  bingcomimg = gtk.Image()
  bingcomimg.set_from_icon_name("web-browser", 24)
  bingcom = gtk.ImageMenuItem('Go to Bing.com')
  bingcom.set_image(bingcomimg)
  bingcom.set_always_show_image(True)
  bingcom.connect('activate', gobingcom)
  
  bpotdimg = gtk.Image()
  bpotdimg.set_from_icon_name("image-x-generic", 24)
  bpotdapp = gtk.ImageMenuItem('Open App')
  bpotdapp.set_image(bpotdimg)
  bpotdapp.set_always_show_image(True)
  bpotdapp.connect('activate', openapp)
  
  openimg_img = gtk.Image()
  openimg_img.set_from_icon_name("image-x-generic", 24)
  openimg = gtk.ImageMenuItem('Open '+os.popen("printf $(date +%F)").read()+".jpg")
  openimg.set_image(openimg_img)
  openimg.set_always_show_image(True)
  openimg.connect('activate', open_img)

  menu.append(openimg)
  menu.append(hr)
  menu.append(hr)
  menu.append(bpotdapp)
  menu.append(bingcom)
  menu.append(aboutbpotd)
  menu.append(hr)
  menu.append(hr)
  menu.append(exittray)

  menu.show_all()
  return menu
  
def quit(_):
  gtk.main_quit()

def bpotdabout(_):
  os.system('xdg-open https://go.microsoft.com/fwlink/?linkid=2118036')

def gobingcom(_):
  os.system('xdg-open https://www.bing.com')

def openapp(_):
  os.system(CURRPATH+"/bpotd-py")
  
def open_img(_):
  os.system('mkdir -p $HOME/Pictures/bpotd')
  curl_xdg = "xdg-open $HOME/Pictures/bpotd/$(date +%F).jpg"
  os.system("curl $(./curl.sh) -o $HOME/Pictures/bpotd/$(date +%F).jpg; "+curl_xdg)

if __name__ == "__main__":
  main()
